project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  sidebar:
    style: docked
    contents:
      - text: "About me"
        href: index.qmd
      - text: "CV"
        href: portfolio.qmd
      - text: "Professional statement"
        href: professional_endeavours.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/chloevdb
        aria-label: GitHub
  page-footer:
    center:
      - text: "Built with love and Quarto"
        href: https://quarto.org

format:
  html:
    theme: default
    css: styles/styles.css
    navigation: true
