project:
  type: website
  output-dir: docs

website:
  title: "Chloé van der Burg"
  navbar:
    left:
      - text: "About me"
        href: index.qmd
      - text: "CV"
        href: portfolio.qmd
      - text: "Professional endeavours"
        href: professional_endeavours.qmd
      - text: "Recipes"
        href: recipes/index.qmd
    right:
      - icon: github
        href: https://github.com/chloevdb
        aria-label: GitHub
  page-footer:
    border: true
    left: "&#169; 2025 Chloé van der Burg"
    right: "Made with ︎♥️ & [Quarto](https://quarto.org)"

format:
  html:
    theme: default
    css: styles/styles.css
    toc: true
    toc-depth: 3
    navigation: true
