---
title: "index"
author: "Chloé van der Burg"
format: html
editor: visual
---

## About me

Throughout my academic career I have built a broad skillset in research, teaching and learning, project management and mentorship. I am passionate about fostering student learning and I deeply value early career researcher development. In my current role I have actively contributed to this through multiple volunteer roles at the University. I have worked in many diverse team environments and I enjoy developing and driving new collaborative projects, through which I have come to highly appreciate the unique backgrounds, knowledge, and perspectives that each team member brings to the table. I have strong expertise in end-to-end transcriptomics, where I have honed my problem-solving skills, particularly in troubleshooting bioinformatic challenges and adapting to new tools and techniques. I am also proficient in complex molecular techniques, such as RNA extraction, sequencing preparation, and single-cell library preparation, which demonstrates my ability to work with challenging molecular protocols, as well as my meticulous approach to my work.
